{% set name = "molecule-docker" %}
{% set version = "1.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/molecule-docker-{{ version }}.tar.gz
  sha256: a16f3bb734eb1d5ec28fa3bb678854bda7cb142968467fc8f4f31a518cd4555f

build:
  number: 1
  skip: true  # [py < 37 or win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools_scm >=1.15.0
    - setuptools_scm_git_archive >=1.0
  run:
    - docker-py >=4.3.1
    - molecule >=3.0.2
    - python
    - python-selinux  # [linux]
    - ansible-compat

test:
  imports:
    - molecule_docker
    - molecule_docker.test
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ansible-community/molecule-docker
  summary: Molecule aids in the development and testing of Ansible roles
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschoonj
